name: master

on:
  push:
    branches:
      - master

jobs:

  #--------------------------
  # BUILD
  #--------------------------
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.3.4

      - name: Install dependencies
        run: flutter pub get

      - name: Setup credentials
        run: |
          mkdir -p ~/.pub-cache
          cat <<EOF > ~/.pub-cache/credentials.json
          {
            "accessToken":"${{ secrets.PUB_ACCESS_TOKEN }}",
            "refreshToken":"${{ secrets.PUB_REFRESH_TOKEN }}",
            "idToken":"${{ secrets.PUB_ID_TOKEN }}",
            "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
            "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
            "expiration": 1633859335782
          }
          EOF

      - name: Analyse
        run: flutter analyze

      - name: Dry Run
        run: dart pub publish --dry-run

#      - name: Deployment
#        run: dart pub publish -f

